DoapSoapRevamped/DoapSoap.WebApp/Models/LocationInventoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DoapSoap.WebApp.Models
{
    public class LocationInventoryViewModel
    {
        [DisplayName("Product Name")]
        [Required]
        public string ProductName { get; set; }

        [DisplayName("Spice Level")]
        [Required]
        public string Spice { get; set; }

        [DisplayName("Price")]
        [Required]
        public decimal Price { get; set; }

        [DisplayName("Quantity")]
        [Required]
        public int Quantity { get; set; }
    }
}

DoapSoapRevamped/DoapSoap.WebApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoapSoap.BusinessLogic.Interfaces;
using DoapSoap.DataAccess.Repositories;
using DoapSoap.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace DoapSoap.WebApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _repo;

        //private readonly NLog.ILogger _logger = LogManager.GetCurrentClassLogger();

        public CustomerController(ICustomerRepository repo)
        {
            //_logger = logger;
            _repo = repo;
        }

        // Display list of customers
        public ActionResult AllCustomers()
        {
            IEnumerable<BusinessLogic.Models.Customer> customers = _repo.GetAllCustomers(null);

            var viewmodels = customers.Select(c => new CustomerViewModel
            {
                Id = c.ID,
                FirstName = c.FirstName,
                LastName = c.LastName,
                Phone = c.Phone
            });

            //_logger.Info("Viewing Customers");

            return View(viewmodels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllCustomers(string SearchName)
        {
            // Redirect from customer page to search customer page with a string (the customer name to be searched)
            return RedirectToAction("Search", new { search = SearchName });
        }

        // Display specific customer's Order History and details of order
        public ActionResult OrderHistory(int id)
        {
            IEnumerable<BusinessLogic.Models.Order> orders = _repo.GetOrdersWithProductDetails(id);

            string customerName = _repo.GetCustomer(id).Name;

            ViewData["CustomerLogName"] = customerName;

            // Populate each order history view with their own list of product details
            var viewmodels = orders.Select(c => new OrderHistoryViewModel
            {
                Id = c.ID,
                LocationName = c.Location.Name,
                Time = c.TimePlaced,
                CustomerName = c.Customer.Name,
                ProductList = c.ProductList.Select(i => new OrderDetailsViewModel
                {
                    ProductName = i.Key.Name,
                    Spice = i.Key.Spice.Name,
                    Quantity = i.Value,
                    Price = i.Key.Price
                })
            });

            //_logger.Info($"Viewing {customerName}'s Order History");

            return View(viewmodels);
        }



        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }


        /// <summary>
        /// Create new customer
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Create new instance of customer from the viewmodel
                    var newCustomer = new BusinessLogic.Models.Customer
                    {
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        Phone = viewModel.Phone
                    };

                    // Add to db via repo
                    _repo.AddCustomer(newCustomer);
                    //_logger.Info("Added new customer");

                    return RedirectToAction(nameof(AllCustomers));
                }
                return View(viewModel);

            }
            catch
            {
                //_logger.Debug(ex.Message);
                Console.WriteLine("Invalid Customer info");
                return View();
            }
        }

        [HttpPost]
        public ActionResult Search(string search)
        {
            var customers = _repo.GetAllCustomers(search);
            ViewData["SearchName"] = search;
            var models = new List<CustomerViewModel>();
            foreach(var customer in customers)
            {
                models.Add(new CustomerViewModel
                {
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    Phone = customer.Phone
                });
            }
            return View(customers);
        }
    }
}

DoapSoapRevamped/DoapSoap.WebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoapSoap.BusinessLogic.Interfaces;
using DoapSoap.BusinessLogic.Models;
using DoapSoap.DataAccess.Repositories;
using DoapSoap.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace DoapSoap.WebApp.Controllers
{
    public class OrderController : Controller
    {
        private ICustomerRepository _crepo;
        private ILocationRepository _lrepo;
        private IOrderRepository _orepo;
        //private readonly NLog.ILogger _logger = LogManager.GetCurrentClassLogger();


        public OrderController(ICustomerRepository crepo, ILocationRepository lrepo, IOrderRepository orepo)
        {
            _crepo = crepo;
            _lrepo = lrepo;
            _orepo = orepo;
        }

        public IActionResult PlaceOrder()
        {

            var viewmodel = new PlaceOrderViewModel
            {
                locations = _lrepo.GetAllLocations(),
                customers = _crepo.GetAllCustomers(),
                selectedOptions = false,
            };

            // If we come to this page but the cart isn't empty, we need to put the products back into their respective place
            if (HttpContext.Session.GetObject<Dictionary<int, int>>("Cart") != null)
            {
                // Get existing cart, location it was taken from
                var cart = HttpContext.Session.GetObject<Dictionary<int, int>>("Cart");
                var locationID = HttpContext.Session.GetObject<int>("SelectedLocationID");
                var location = _lrepo.GetLocation(locationID);
                location.Inventory = _lrepo.GetLocationInventory(locationID);

                // Increase location inventory quantities corresponding with the cart
                foreach (var item in cart)
                {
                    var product = location.Inventory.Where(i=>i.Key.ID == item.Key).First().Key;
                    location.Inventory[product] += item.Value;
                }
                // Save changes to the database
                _lrepo.UpdateLocationInventory(location);
                _lrepo.SaveChanges();
            }

            HttpContext.Session.SetObject("Cart", null);

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PlaceOrder(PlaceOrderViewModel model)
        {
            // locId and custId should hold the id of the selected from before
            int locId = int.Parse(Request.Form["sel1"]);
            int custId = int.Parse(Request.Form["sel2"]);
            model.selectedLocation = _lrepo.GetLocation(locId);
            model.selectedCustomer = _crepo.GetCustomer(custId);

            model.locations = _lrepo.GetAllLocations();
            model.customers = _crepo.GetAllCustomers();

            model.selectedOptions = true;

            var BLmodel = _lrepo.GetLocationInventory(locId);
            var viewmodel = BLmodel.Select(i => new LocationInventoryViewModel
            {
                ProductName = i.Key.Name,
                Spice = i.Key.Spice.Name,
                Price = i.Key.Price,
                Quantity = i.Value
            });


            model.Products = viewmodel;

            var addProductModel = new AddProductViewModel
            {
                SelectedCustomer = model.selectedCustomer,
                SelectedLocation = model.selectedLocation
            };

            model.selectedLocation.Inventory = _lrepo.GetLocationInventory(locId);
            TempData["SelectedCustID"] = model.selectedCustomer.ID;
            TempData["SelectedLocID"] = model.selectedLocation.ID;


            return RedirectToAction(nameof(AddProducts));
        }



        /// <summary>
        /// Takes you to view where you can start adding products to your order
        /// </summary>
        /// <returns></returns>
        public IActionResult AddProducts()
        {
            int locID = (int)TempData["SelectedLocID"];
            int custID = (int)TempData["SelectedCustID"]; 

            var location = _lrepo.GetLocation(locID);
            var locationInv = _lrepo.GetLocationInventory(location.ID);

            var customer = _crepo.GetCustomer(custID);

            var newHiddenInventory = new Dictionary<int, int>();
            foreach (var item in locationInv)
            {
                newHiddenInventory.Add(item.Key.ID, item.Value);
            }

            var model = new AddProductViewModel
            {
                SelectedCustomer = customer,
                SelectedLocation = location,
                Inventory = locationInv,
            };

            HttpContext.Session.SetObject("SelectedLocationID", locID);
            HttpContext.Session.SetObject("SelectedCustomerID", custID);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProducts(AddProductViewModel model)
        {


            int locID = (int)TempData["SelectedLocID"];
            int custID = (int)TempData["SelectedCustID"];

            var location = _lrepo.GetLocation(locID);
            var customer = _crepo.GetCustomer(custID);
            var oldInventory = _lrepo.GetLocationInventory(locID);
            location.Inventory = oldInventory;

            // Grab the product and amount selected, then add to cart
            int quantity = model.SelectedQuantity;
            var product = oldInventory.Keys.Where(p => p.ID == model.SelectedProductID).First();

            // Update inventory with model's selected quantity and location
            try
            {
                location.RemoveFromInventory(product, quantity);
                _lrepo.UpdateLocationInventory(location);
                _lrepo.SaveChanges();
            }
            catch
            {
                Console.WriteLine("Could not remove from inventory");

                // Recreate the cart to display without decrementing the inventory
                var sameCart = new Dictionary<int, int>();
                var sameDisplayCart = new Dictionary<Product, int>();
                var sameCartVM = new List<CartViewModel>();

                // If there's stuff in the cart, populate
                if (HttpContext.Session.GetObject<Dictionary<int, int>>("Cart") != null)
                {
                    var currentCart = HttpContext.Session.GetObject<Dictionary<int, int>>("Cart");
                    sameCart = new Dictionary<int, int>(currentCart);

                    foreach (var item in sameCart)
                    {
                        var newProduct = _crepo.GetProduct(item.Key);
                        sameDisplayCart.Add(newProduct, item.Value);
                        sameCartVM.Add(new CartViewModel
                        {
                            ProductName = newProduct.Name,
                            Price = newProduct.Price,
                            Quantity = item.Value,
                            SpiceLevel = newProduct.Spice.Name
                        });
                    }
                }

                var returnModel = new AddProductViewModel
                {
                    SelectedCustomer = customer,
                    SelectedLocation = location,
                    DisplayCart = sameDisplayCart,
                    Inventory = location.Inventory,
                    _Cart = sameCartVM,
                    InvalidQuantityTaken = true
                };
                return View(returnModel);
            }

            // Configure new cart
            var newCart = new Dictionary<int, int>();

            if (HttpContext.Session.GetObject<Dictionary<int, int>>("Cart") != null)
            {
                var currentCart = HttpContext.Session.GetObject<Dictionary<int, int>>("Cart");
                newCart = new Dictionary<int, int>(currentCart);
            }
            try
            {
                // Add new product id to dictionary
                newCart.Add(product.ID, quantity);
            }
            catch
            {
                // Catch if product is already in dictionary, then just increase the quantity
                newCart[product.ID] += quantity;
            }
            HttpContext.Session.SetObject("Cart", newCart);

            // populate display cart using our persistent cart
            var newDisplayCart = new Dictionary<Product, int>();
            var newCartVM = new List<CartViewModel>();

            foreach (var item in newCart)
            {
                var newProduct = _crepo.GetProduct(item.Key);
                newDisplayCart.Add(newProduct, item.Value);
                newCartVM.Add(new CartViewModel
                {
                    ProductName = newProduct.Name,
                    Price = newProduct.Price,
                    Quantity = item.Value,
                    SpiceLevel = newProduct.Spice.Name
                });
            }


            // Model we're sending to view
            var newModel = new AddProductViewModel
            {
                SelectedCustomer = customer,
                SelectedLocation = location,
                DisplayCart = newDisplayCart,
                Inventory = location.Inventory,
                _Cart = newCartVM
            };

            return View(newModel);
        }

        /// <summary>
        /// Takes cart, customer id, and store location and populates an order object, then attempts to add to db
        /// </summary>
        /// <returns></returns>
        public IActionResult ConfirmOrder()
        {
            // Translate the cart into the order inventory
            Dictionary<Product, int> orderInventory = new Dictionary<Product, int>();
            var cart = HttpContext.Session.GetObject<Dictionary<int, int>>("Cart");
            foreach (var item in cart)
            {
                var product = _crepo.GetProduct(item.Key);

DoapSoapRevamped/DoapSoap.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super Supper Soup Coop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />

    <!-- Im going to attempt to input my css like this-->
    <link href="@Url.Content("~/Styles/main.css")" rel="stylesheet" type="text/css" />
    @RenderSection("Styles", false)
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Super Supper Soup Coop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="PlaceOrder">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="AllLocations">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="AllCustomers">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Super Supper Soup Coop - Drink up, bois.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DoapSoapRevamped/DoapSoap.WebApp/Views/Shared/_LocationInventory.cshtml
@model IEnumerable<LocationInventoryViewModel>

<h1>Inventory</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Spice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Quantity)
                </td>
            </tr>
        }
    </tbody>
</table>